language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "GjJylSeY0Wcx2q59O5tWuDfKk2L1agDcS0ClTVYzbY/8+z2oIeYQOLZGbnLzgzGxs9U1E/Py6YiGI43xiGcWV+iP+Dnixwnp5Ec4k6HkKzYNBBFKw6VwS2LdnaV02uy6H8RhPmjkRLpviRZTqY5ztnAVN2HTGFlAvhzPiftyL6KFrc0JKemAjPX6KVyRfFOKGYn4rhmImg6u0A58qMYrpenQeaI8kuHGDyfOcQmAr+mvYuPs/7N9PDGXDb+ahe1Juxfa9Nv+YnPDXOKb0nDqGzROiFNuNkqEJ87a04MhKhgJ0gtJbPQ0wFsJhXKXg/ykh5oAHHEqM1N0//tttBBsZ4oXcB/4bVQqZJV2INB4fagXxx0njKCowT0wd2JtdNPQfOti4tw9Olr5tNgxZRnIlK7jJH/+s9UUhk31PX9jJCHSeEtnn9Kq/2/unmbbeuHH99Fl7Wuwp2pK23tO3VvSrxhMtaCvfVtBRpDx9/Ev+jM2xprOIxHLU29wtvHqXY2JnKPNpmXROJkbp61jqyIbuQygD2YZLIb4iepDEGVBUrt0mzR/WUPbAt+yfawdid1ciGBU7px9RnNOiLpboZzcT2L2JnxCbZGg4M3Ayz3MchthoB22KAl8cvUEzVFBDwgEDqOtcC24J9SXGiIvseMMSrQP3ii85EETzj6RGn6jEwU="
  secret_access_key:
    secure: "xcUZ46zzFLzIZdu30NH0HYLIkncGXhBkPklo37lGhsGiZqwXeMppqi2Vqh2MtJKxENSEAiW17OKGxEvUr5bVOSsnEh/GGM7xZK3J2J8bqq7DFXeZqjrYTPPQ8Jxvh8mIzZvY/xaSDvE/eV9x4jBqGSE48ZSdHCN9IU+wJ+75HERnZ9XQcVYawGLJrWnidfxUHii5WVWO7ZqzL+aKtDnJ0PYZtilBotMavn4qEet2wqECbN7ErhfDJON1hoYtRTr2c7qnu7iyGngczgmYiMfn7kkxyG8Je9MCy8tnIPH1MnObDi/wRsTKwIcTg7Gp6jIyaefFeIqWvxsrwQ4ZbKg38CleLnYO9WcUCP8bI0xAoES5kMJsjefK2WrwclSwmf2bMZouyebtxsM4ttDcHqqSFZhFcXzYiNsGxYfSl2KDdq2SBXn1DOhI/lSX0M0QCSySZnaVoRfkGSfguTzbLG5/9RDaLnQa1hnEplukeT+Vy7BvIUWffBcpP6VHoQ4Zr7g6YHjk/xFwTYi+mXTnnMAUtb8GXjdxD7JqgzmXsR0W7cKaTmaqrrtF8CPBeeWtWtspjIbHYcsc0hmapocsS4ch0VETriyxbQZq4SsFN8+lRYLclNmYt7Tetxhv2gSE7p0eeAUfElSpFsTqhXBXR+pwP5Ws0n5Ner0M0V8Ncp+oVt4="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  upload_dir: projects/text-to-speech
