language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "xZJW15uY6ZO2dTwIFTHwCWpazis3UPx270mwYwLqtP/xVMQ/+5i77FCgbsZmyr6Wnr3a7h+GxYXqqYSGv95O5GgGW1vwunyIkdHq6pL7hkls4b7gsR60e/AXzq/ntfPgkEJtE4GflnGfsneBvQOP35MVB5+s0lsDDlZ7Vepi2vs4zgi/eBgY5XrlBmk3rFcQgcgKX1DeD0MqPjmLzJTxOI2Uuor9lIMMIyvpaKfWgS0DvSXhhtKUR4qUVRL4rj6unZmXMAeNE/P+2t/Gbi7D8yVjSNMswix7CpS0O+WQCKdKqaCEyRf1sTamMi0p1b0xoN4JVe7sgWMLMoknjRZR5MPhwpJ2R7RLF4k+Uok/6lx/hsI35/F8+uuVlco74fsGHMMPqvmeVyB5r59da4ZEmR5iptVLCO5hizIYsUasyA5G7V5HwVRKbaaoxRxxcXEkeaJVaXmkKqbPjN2IfBcCFzE6ID2etA/mOIqoxH2JmVCFr53QB62tDhBnr4pqg5Wmxlfn0HOuBFyQYOcTNi7CBHBP0VXGXUHcJHBDJVxpS7Ug7HKBr1zvhEbrnqo/B/oQQ866EWHXOpZ3WI+FLryPKNJuxUxYEHdLV0u29xeFWOXMIlQTw1WxxrMjFcK1Au4ck9iG3+3DRIDr4ultZQx+azUW/jFDXOAh+4VAxa3QjC8="
  secret_access_key:
    secure: "TFwl2b17eEqvgnktHofH5Mb+OxVuKrqMZ8z48Q7AUX8gGjdoayfX0FFYJHoZXlPuUFUwZqIf8HXCwNMPSPiaiYojYUQTE23c8tYdb74VmRMbRVK2AJ4xYn6qcjvAEDyA73gIyypVrDU3vyHE1miHsu3BTdsgCAQBVOwVbF9V1BnIPlTox1MXSfi7FKDwF0NtbrZm3/ElWU95xVbr87DGKnUT1LvsdZEVr+M7X91qR4N2VkSxEwVVwI60LrwrK7O5wd/SxlVKp68aP6abtPtePeXVy6ejHhZi8iImsWDUOGCPXMiwoIBx+yKAQ+VQVdHkhfvNpp5Ah+5sMe/yyWfwX9iQQaSIO+9jso8NFEpYCpaSuvKvoRoxoaUB6TRK/Y/glakNu+lMRQNSzWZH24Vc8qmwTD8Ayal90O69mUlARoimaFLb52zmFiWWroCAeGAiPJebgdh99cM1vYXhm+RgL3nf1i5PpOr23EtO/pRX0BrKPT5TjN/JZftdFgw/+y6WudlIm6tl6JCo3LVXQb2NBJM138j+YDpX+JwPvKL1Xwy0f5JMBYXQWpIVFOoBLOVztTTzqYawcT6aDfs17+GhoY6TW2wTxiC9EUu5lNjPAM+ewgtufJUhm+9wgCT0bJp6lfXOtoXnqRuVisV0/Aekd0ZA4Bc5aLmi3yogvRAcx9s="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  upload_dir: projects/text-to-speech
